import { createUser } from './signUpLogic.js';

export const signUpFunction = () => {
  const rootUp = document.getElementById('rootSignUp');
  const headerUp = document.createElement('header');
  const titleUp = document.createElement('h1');
  titleUp.innerHTML = 'Tejer & Punto';
  headerUp.appendChild(titleUp);
  rootUp.appendChild(headerUp);
  const mainUp = document.createElement('main');
  const inputEmailUp = document.createElement('input');
  inputEmailUp.setAttribute('id', 'emailUp');
  inputEmailUp.setAttribute('type', 'email');
  inputEmailUp.setAttribute('placeholder', 'Correo electrónico');
  mainUp.appendChild(inputEmailUp);
  const inputPasswordUp = document.createElement('input');
  inputPasswordUp.setAttribute('id', 'passwordUp');
  inputPasswordUp.setAttribute('type', 'password');
  inputPasswordUp.setAttribute('placeholder', 'Contraseña');
  mainUp.appendChild(inputPasswordUp);
  const buttonCreateUser = document.createElement('button');
  buttonCreateUser.innerHTML = 'Regístrate';
  buttonCreateUser.setAttribute('id', 'buttonCreateUser');
  buttonCreateUser.addEventListener('click', createUser);
  mainUp.appendChild(buttonCreateUser);
  const termsText = document.createElement('p');
  termsText.innerHTML = 'Al registrarte, aceptas las <a href="">Condiciones</a> de Tejer & Punto.';
  mainUp.appendChild(termsText);
  const sendToSignInText = document.createElement('p');
  sendToSignInText.innerHTML = '¿Ya tienes una cuenta? <a href="">Inicia sesión</a>.';
  mainUp.appendChild(sendToSignInText);
  const separationTextUp = document.createElement('p');
  separationTextUp.innerHTML = '- o -';
  mainUp.appendChild(separationTextUp);
  const buttonToGoogleUp = document.createElement('button');
  buttonToGoogleUp.innerHTML = 'Ingresa con Google';
  mainUp.appendChild(buttonToGoogleUp);
  rootUp.appendChild(mainUp);
};
