import { loginUser } from './signInLogic.js';
import { googleAccess } from './googleSignIn.js';

export const signInView = () => {
  const containerIn = document.createElement('div');
  const headerIn = document.createElement('header');
  const titleIn = document.createElement('h1');
  titleIn.innerHTML = 'Tejer & Punto';
  headerIn.appendChild(titleIn);
  containerIn.appendChild(headerIn);
  const mainIn = document.createElement('main');
  const inputEmailIn = document.createElement('input');
  inputEmailIn.setAttribute('id', 'emailIn');
  inputEmailIn.setAttribute('type', 'email');
  inputEmailIn.setAttribute('placeholder', 'Correo electrónico');
  mainIn.appendChild(inputEmailIn);
  const inputPasswordIn = document.createElement('input');
  inputPasswordIn.setAttribute('id', 'passwordIn');
  inputPasswordIn.setAttribute('type', 'password');
  inputPasswordIn.setAttribute('placeholder', 'Contraseña');
  mainIn.appendChild(inputPasswordIn);
  const buttonLoginUser = document.createElement('button');
  buttonLoginUser.innerHTML = 'Inicia sesión';
  buttonLoginUser.setAttribute('id', 'buttonLoginUser');
  buttonLoginUser.addEventListener('click', loginUser);
  mainIn.appendChild(buttonLoginUser);
  const separationTextIn = document.createElement('p');
  separationTextIn.innerHTML = '- o -';
  mainIn.appendChild(separationTextIn);
  const buttonToGoogleIn = document.createElement('button');
  buttonToGoogleIn.innerHTML = 'Ingresa con Google';
  buttonToGoogleIn.addEventListener('click', googleAccess);
  mainIn.appendChild(buttonToGoogleIn);
  const sendToSignUpText = document.createElement('p');
  sendToSignUpText.innerHTML = '¿No tienes una cuenta? <a href="#/signup">Regístrate</a>.';
  mainIn.appendChild(sendToSignUpText);
  containerIn.appendChild(mainIn);
  return containerIn;
};
